import { UserWidget } from "@/features/user/widget";
import { Logo } from "@/ui/logo";
import { type NextPage } from "next";
import Head from "next/head";
import { CreateCategory } from "@/features/category/create-category";
import { Index } from "@/features/category/select-category";


const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen">
        <div className="container mx-auto flex items-center justify-between p-6">
          <Logo />
          <div className="flex items-center">
            <Index />
            <CreateCategory />
          </div>
          <UserWidget />
        </div>
      </main>
    </>
  );
};

export default Home;
